Bist07/EquiFood-App-A

README.md
Added some links to basic info to aid in setup of the techstack
=> Added setup instructions

README.md
Added a link to Expressjs setup and install instructions
=> Added Expressjs install information to tech stack

README.md
Added a link that leads to MariaDB's explanation of installation and basic functions
=> Added MariaDB setup instructions to tech stack

DDL for "Food".txt
*THIS IS A VERY EARLY DRAFT*
This document will see many changes and revisions as development continues. Meant to serve as an early jumping off point
=> DDL for Food table

DDL for "Food".txt
Added IF NOT EXISTS to food table
=> Update DDL for "Food".txt

DDL for "Restaurant" table.txt
added IF NOT EXISTS to restaurant table
=> Update DDL for "Restaurant" table.txt

DDL/DDL For Admin.sql
added column to track total donations across the entire program
=> Added donations column

DDL/DDL For Food.sql, DDL/DDL for Restaurant.sql
variable sizes were too large, added column to store images for restaurants and food items
=> Fixes issues with DDL

Code/src/App.tsx, Code/src/components/reserveFood.tsx, Code/src/pages/Cart.tsx, Code/src/pages/Profile.tsx, Code/src/pages/Tab1.tsx, Code/src/pages/Tab2.tsx, Code/src/pages/Tab3.tsx, Code/src/pages/Tab4.tsx, Code/src/pages/food/Item1.tsx, Code/src/pages/food/Item2.tsx, Code/src/pages/food/Item3.tsx, Code/src/pages/food/Item4.tsx, Code/src/pages/food/Item6.tsx, Code/src/pages/food/Item7.tsx
Added in food options into stores. Also added in cart tab but no functionality yet
=> Populated stores with food options

Code/src/App.tsx, Code/src/components/CartItem.tsx, Code/src/components/Navbar.tsx, Code/src/components/StoreItem.tsx, Code/src/components/reserveFood.tsx, Code/src/context/ShoppingCartContext.tsx, Code/src/data/items.json, Code/src/hooks/useLocalStorage.ts, Code/src/pages/Cart.tsx, Code/src/pages/Tab2.tsx, Code/src/pages/Tab3.tsx, Code/src/pages/Tab4.tsx, Code/src/pages/food/Item1.tsx, Code/src/pages/food/Item2.tsx, Code/src/pages/food/Item3.tsx, Code/src/pages/food/Item4.tsx, Code/src/pages/food/Item6.tsx, Code/src/pages/food/Item7.tsx, Code/src/pages/tab.css
Added in Shopping Cart functionality. Refactored code to allow for easier card creation
=> Shopping cart

DDL/DDL for Restaurant.sql
switched datatype of columns, storeDescription and address.
=> changed varchar to text for storeDescriptions and address.

DDL/DDL for Restaurant.sql
Added some example restaurants to aid in development and implementation.
=> Added INSERT statements for Example Restaurants

DDL/DDL for Restaurant.sql
Added longitude and latitude columns to Restaurant DDL
=> Added longitude and latitude

EquiFood-A-ReactNative/StackNavigator.js, EquiFood-A-ReactNative/components/TimePicker.js, EquiFood-A-ReactNative/components/ViewCart.js, EquiFood-A-ReactNative/package-lock.json, EquiFood-A-ReactNative/package.json, EquiFood-A-ReactNative/screens/OrderPage.js
Still working on pickup time system. Will get it done on the weekend
=> Implemented basic Order Received page. 

EquiFood-A-ReactNative/data/createRestaurant.js
Server must be running locally for now
=> createRestaurant test function

EquiFood-A-ReactNative/data/addItem.js
Serve must be running locally for now.
This will be the base idea for addition of new items although it will change a lot from this, currently just testing things out.
=> Test function for addition of items

DDL/DDL for Users
This will hold all the info on users
Password datatype will be changed and encrypted, this is just for now
=> Created DDL for Users table

EquiFood-A-ReactNative/App.js, EquiFood-A-ReactNative/StackNavigator.js, EquiFood-A-ReactNative/components/RestaurantCard.js, EquiFood-A-ReactNative/components/stylesR.js, EquiFood-A-ReactNative/data/createRestaurant.js, EquiFood-A-ReactNative/screens/LogIn.js, EquiFood-A-ReactNative/screens/ProfilePage.js, EquiFood-A-ReactNative/screens/RestaurantsView.js
=> renamed files for clarity

DDL/DDL for Users
This column holds the date an account is created, the field is automatically filled on insertion using default CURRENT_TIMESTAMP
=> Added created on column

EquiFood-A-ReactNative/server/routes/Users.js, EquiFood-A-ReactNative/server/server.js
This function will be used for username/pass validation (and other purposes late on)
=> Backend   log in query

EquiFood-A-ReactNative/server/routes/Users.js
Base code for what will be the user creation function.
=> Base User creation function

EquiFood-A-ReactNative/server/routes/customer.js, EquiFood-A-ReactNative/server/server.js
After the database was remade changes where made to ensure the query functions still work for the customer table
=> Fixed customer query after backend changes

EquiFood-A-ReactNative/server/routes/customer.js
=> Small fix to user query

EquiFood-A-ReactNative/server/routes/customer.js
saving progress before switching to tasks suggested by TA
=> Login query

EquiFood-A-ReactNative/screens/RestaurantInfoEditView.js
working on backend link right now
=> Restaurant Insert Front End

EquiFood-A-ReactNative/StackNavigator.js, EquiFood-A-ReactNative/config.js, EquiFood-A-ReactNative/screens/AdminLogIn.js, EquiFood-A-ReactNative/screens/FoodEditView.js, EquiFood-A-ReactNative/screens/FoodInsertView.js, EquiFood-A-ReactNative/screens/RegisterAdmin.js, EquiFood-A-ReactNative/screens/RestaurantInsertView.js, EquiFood-A-ReactNative/server/routes/RestaurantOwner.js, EquiFood-A-ReactNative/server/routes/admin.js, EquiFood-A-ReactNative/server/server.js
=> Admin Register
